#!/bin/bash

# Invoked from world directory with its own name as parameter

this="$1"
opponent=$(cat state/0/$this/opponent)

if [ -e state/previous ]; then
	my_play=$(cat state/previous/$opponent/play)
else
	my_play=cooperate
fi

echo -e "---\nplay: $my_play"

