#!/bin/bash

dyn=$1
num=$2

if [ $num -eq 1 ]; then
    who=alice
elif [ $num -eq 2 ]; then
    who=betty
else
    echo "Error: \"only two players are supported currently\""
fi

$dyn $who

cat <<EOF
---
trent:
    players:
        $who: $dyn
EOF

