#!/bin/bash

dyn=$1 # name of directory under $world/dynamics
num=$2 # instance number

  if [ $num == 0 ]; then who=alice
elif [ $num == 1 ]; then who=betty
else echo "Error: \"only two players are supported\""
fi

cat <<EOF
---
trent:
    players:
        $who: $dyn
EOF

