#!/bin/bash

gen=$1

if [ $num -eq 1 ]; then
    who=alice
elif [ $num -eq 2 ]; then
    who=betty
else
    echo "Error: \"only two players are supported currently\""
fi

$gen $who

cat <<EOF
---
trent:
    players:
        $who: $gen
EOF

